### PR TITLE
About page

### PR DESCRIPTION
**Pull request by prineth**

### CODE REVIEW

**Review by Harindu973 — COMMENTED** [review]
Is there any changes?

**Review by Harindu973 — CHANGES_REQUESTED** [review]
Please check your changes submitted correctly.

**Review by BuddhikaD — COMMENTED** [review]
what's the change malli? I don't see any change in this..

**Comment by BuddhikaD** [comment]
Malli please update your branch using the main branch, your branch doesn't match the main this is why the eslintcache push to that way..

**Pull request closed without merging**
